import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { StoreProvider } from "@/../redux/store";
import AuthProvider from "@/components/provider/auth";
import ProtectedPage from "@/../routes/protected-routes";

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Ticketing",
  description: "Generated by peik",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <StoreProvider>
          <AuthProvider>
            <ProtectedPage>{children}</ProtectedPage>
          </AuthProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
